language: php

sudo: required

before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update
  - sudo apt-get install ffmpeg
  - phpenv config-rm xdebug.ini
install:
  - composer update --prefer-source

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
